--[[
    StatIds

    AUTO-GENERATED from data/stat_defs.json - do not hand edit ids here,
    regenerate this file instead whenever stat_defs.json changes (new
    option rows added by design should just append; do not reuse or
    reorder existing ids, since they are stored per-item in the DB).

    Naming convention:
      - Flat point-buy grants named "+ X" with percent=0 (e.g. "+ Strength")
        drop the prefix here -> STRENGTH, SPEED, DAMAGE, EXP, ATTACK_SKILL...
      - Genuine percent MODIFIERS named "+ X" with percent=1 keep a PLUS_
        prefix -> PLUS_PHYSICAL_DAMAGE, PLUS_LIFE, PLUS_DEFENSE, PLUS_MANA...
      - Duplicate display names ("Evade", "Enchanted", "Explode", "Bolt", ...
        appear more than once with different ids) get a numeric suffix
        (EVADE / EVADE_2). Check StatDefs.get(id).color to tell them apart
        if your content needs to distinguish them.
      - A handful of rows have a name that can't become a valid identifier
        (or contain non-ASCII text) -- those fall back to STAT_<id>; see the
        trailing comment for the real display name.
]]

return {
    PHYSICAL_DAMAGE = 0, -- Physical Damage
    ICE_DAMAGE = 1, -- Ice Damage
    FIRE_DAMAGE = 2, -- Fire Damage
    LIGHTNING_DAMAGE = 3, -- Lightning Damage
    POISON_DAMAGE = 4, -- Poison Damage
    DARKNEST_DAMAGE = 5, -- Darknest Damage
    HOLY_DAMAGE = 6, -- Holy Damage
    PLUS_PHYSICAL_DAMAGE = 7, -- + Physical Damage
    PLUS_ICE_DAMAGE = 8, -- + Ice Damage
    PLUS_FIRE_DAMAGE = 9, -- + Fire Damage
    PLUS_LIGHTNING_DAMAGE = 10, -- + Lightning Damage
    PLUS_POISON_DAMAGE = 11, -- + Poison Damage
    PLUS_DARKEST_DAMAGE = 12, -- + Darkest Damage
    PLUS_HOLY_DAMAGE = 13, -- + Holy Damage
    DEFENSE = 14, -- Defense
    PLUS_DEFENSE = 15, -- + Defense
    PHYSICAL_RESIST = 16, -- Physical resist
    ICE_RESIST = 17, -- Ice resist
    FIRE_RESIST = 18, -- Fire resist
    LIGHTNING_RESIST = 19, -- Lightning resist
    POISON_RESIST = 20, -- Poison resist
    DARKEST_RESIST = 21, -- Darkest resist
    HOLY_RESIST = 22, -- Holy resist
    STRENGTH = 23, -- + Strength
    DEXTERITY = 24, -- + Dexterity
    VITALITY = 25, -- + Vitality
    INTELLIGENCE = 26, -- + Intelligence
    PLUS_LIFE = 27, -- + Life
    PLUS_MANA = 28, -- + Mana
    REPLENISH_LIFE = 29, -- Replenish Life
    REGENERATE_MANA = 30, -- Regenerate Mana
    LIFE_STEAL = 31, -- Life steal
    MANA_STEAL = 32, -- Mana steal
    CRITICAL_RATE = 33, -- Critical rate
    EVADE = 34, -- Evade
    REFLECT_DAM = 35, -- Reflect Dam
    PIERCING_ATTACK = 36, -- Piercing Attack
    ATTACK_SKILL = 37, -- + Attack Skill
    DEFEND_SKILL = 38, -- + Defend Skill
    SPECIAL_SKILL = 39, -- Special Skill
    BASIC_DAMAGE = 40, -- Basic Damage
    RAGE = 41, -- Rage
    RAGE_DURATION = 42, -- Rage duration
    PUT_EGGS_IN_THE_STABLE_TO_HATCH = 43, -- Put eggs in the stable to hatch
    REGENT_MP = 44, -- Regent mp
    SLEEP = 45, -- Sleep
    STUN = 46, -- Stun
    REGENT_HP = 47, -- Regent hp
    DAMAGE = 48, -- + damage
    EXP = 49, -- + Exp
    SPEED = 50, -- + speed
    PLUS_EXP_MORE = 51, -- + Exp more
    PLUS_GOLD = 52, -- + gold
    THIEFT = 53, -- Thieft
    KNIGHT = 54, -- Knight
    MERCHANT = 55, -- Merchant
    DARKEST_DAMAGE_APPEAR = 56, -- Darkest Damage appear
    HOLY_DAMAGE_APPEAR = 57, -- Holy Damage appear
    HOLE_1 = 58, -- Hole 1
    HOLE_2 = 59, -- Hole 2
    HOLE_3 = 60, -- Hole 3
    ENCHANTED = 61, -- Enchanted
    GHOST_RESIST = 62, -- Ghost resist
    TRANSFIGURE = 63, -- Transfigure
    PLUS_HOLY_DAMAGE_APPEAR = 64, -- + Holy Damage appear
    PLUS_DARKNEST_DAMAGE_APPEAR = 65, -- + Darknest Damage appear
    FREEZE = 66, -- Freeze
    ICY_SNOW = 67, -- Icy snow
    EXTEND = 68, -- Extend
    TRANSFORM = 69, -- Transform
    SELL_PRICE = 70, -- Sell Price
    EFFECT = 71, -- Effect
    DARKNEST_CRIT_DAMAGE_APPEAR = 72, -- Darknest crit Damage appear
    PLUS_DARKNEST_CRIT_DAMAGE = 73, -- + Darknest crit  Damage
    HOLY_CRIT_DAMAGE_APPEAR = 74, -- Holy crit Damage appear
    PLUS_HOLY_CRIT_DAMAGE = 75, -- + Holy crit  Damage
    PCT_FOR_FIREBALL = 76, -- % for Fireball
    FIREBALL = 77, -- -Fireball
    PCT_FOR_FROST_BITE = 78, -- % for Frost Bite
    FROST_BITE = 79, -- -Frost Bite
    DARK_ARMOR = 80, -- Dark armor
    INVISIBLE_MAN = 81, -- Invisible Man
    PCT_FOR_INVISIBLE_MAN = 82, -- % for Invisible Man
    PCT_FOR_QUICKSILVER = 83, -- % for Quicksilver
    QUICKSILVER = 84, -- Quicksilver
    PCT_FOR_SHIELD_OF_MAGIC = 85, -- % for Shield of Magic
    SHIELD_OF_MAGIC = 86, -- Shield of Magic
    PCT_FOR_CHAOS = 87, -- % for Chaos
    CHAOS = 88, -- -Chaos
    PSYCHO = 89, -- Psycho
    PHYSICAL_CHARM = 90, -- Physical Charm
    ICE_CHARM = 91, -- Ice Charm
    FIRE_CHARM = 92, -- Fire Charm
    ELECTIC_CHARM = 93, -- Electic Charm
    POISON_CHARM = 94, -- Poison Charm
    HAND_OF_GOD = 95, -- Hand of God
    HIDE_LINES_MIGHT_HAVE = 96, -- Hide lines might have:
    PCT_FOR_DEEP_WOUND = 97, -- % for Deep wound
    DEEP_WOUND = 98, -- -Deep wound
    EVADE_2 = 99, -- Evade
    IMMORTALS = 100, -- Immortals
    IMMUNITY = 101, -- Immunity
    PHYSICAL_RESIST_2 = 102, -- Physical resist
    HEALING = 103, -- Healing
    HP_UNDER = 104, -- HP Under
    HEALING_HP = 105, -- Healing HP
    IMPERFECTION = 106, -- Imperfection
    PLUSCRITICAL_DAMAGE = 107, -- +Critical Damage
    SPACE = 108, -- Space
    REBORN = 109, -- Reborn
    CLONE = 110, -- Clone
    POWER = 111, -- Power
    KING_CUP_POINTS = 112, -- King Cup points
    MAX_HP_DAMAGE = 113, -- Max HP Damage
    TOTAL_TARGET = 114, -- Total target
    VINH_VIEN = 115, -- vinh vien
    COMBO = 116, -- Combo
    STAT_117 = 117, -- Hộ vệ bóng tối
    STAT_118 = 118, -- Chuyển đổi
    STAT_119 = 119, -- Giảm nội tại
    STAT_120 = 120, -- Thuật hóa giải
    STAT_121 = 121, -- Điểm tặng ngọc
    NO_EXP_GAIN = 122, -- No EXP gain
    AUTO_TRAIN_TIME = 123, -- Auto-Train time
    ENCHANTED_2 = 124, -- Enchanted
    ENCHANTED_3 = 125, -- Enchanted
    ENCHANTED_4 = 126, -- Enchanted
    ENCHANTED_5 = 127, -- Enchanted
    PURE_DAMAGE = 128, -- Pure damage
    DURABILITY = 129, -- Durability
    LUCK = 130, -- Luck
    EXPLODE = 131, -- Explode
    BOLT = 132, -- Bolt
    BLOCK_FIRE_DAMAGE = 133, -- Block fire damage
    BLOCK_POISON_DAMAGE = 134, -- Block poison damage
    BLOCK_PHYSICAL_DAMAGE = 135, -- Block physical damage
    BLOCK_ICE_DAMAGE = 136, -- Block ice damage
    BLOCK_LIGHTNING_DAMAGE = 137, -- Block lightning damage
    STEAL_HP_AFTER_3_HITS = 138, -- Steal HP after 3 hits
    BLEEDING = 139, -- Bleeding
    BLIND = 140, -- Blind
    GET_BURNED_IN_20_SECONDS_COOLDOWN = 141, -- Get burned in 20 seconds, cooldown
    BLACK_SHIELD = 142, -- Black Shield
    EXPLODE_2 = 143, -- Explode
    BOLT_2 = 144, -- Bolt
    BLOCK_FIRE_DAMAGE_2 = 145, -- Block fire damage
    BLOCK_POISON_DAMAGE_2 = 146, -- Block poison damage
    BLOCK_PHYSICAL_DAMAGE_2 = 147, -- Block physical damage
    BLOCK_ICE_DAMAGE_2 = 148, -- Block ice damage
    BLOCK_LIGHTNING_DAMAGE_2 = 149, -- Block lightning damage
    STEAL_HP = 150, -- Steal HP
    BLEEDING_2 = 151, -- Bleeding
    BLIND_2 = 152, -- Blind
    BURN = 153, -- Burn
    BLACK_SHIELD_2 = 154, -- Black Shield
    PURE_DAMAGE_2 = 155, -- Pure damage
    POTENTIAL = 156, -- Potential
    USE_TO_EARN_GIFT = 157, -- Use to earn gift
    FREE_SHOPPING = 158, -- Free Shopping
    ANTI_PK = 159, -- Anti-PK
    THUNDERSTORM = 160, -- Thunderstorm
    FIRE_STORM = 161, -- Fire storm
    CAN_EXTEND = 162, -- Can extend
    PET_EXPIRE = 163, -- Pet expire
    RUINED = 164, -- Ruined
    RUINED_2 = 165, -- Ruined
    DULL = 166, -- Dull
    DULL_2 = 167, -- Dull
    BECOME_INVULNERABILITY_IN_5_SECONDS_COOLDOWN = 168, -- Become invulnerability in 5 seconds, cooldown
    BECOME_INVULNERABILITY_IN_5_SECONDS_COOLDOWN_2 = 169, -- Become invulnerability in 5 seconds, cooldown
    ACCURATE = 170, -- Accurate
    PLATINUM_ARMOR = 171, -- Platinum armor
    PLATINUM_ARMOR_2 = 172, -- Platinum armor
    ANGEL_ARMOR = 173, -- Angel armor
    ANGEL_ARMOR_2 = 174, -- Angel armor
    GUARDIAN_ARMOR = 175, -- Guardian armor
    GUARDIAN_ARMOR_2 = 176, -- Guardian armor
    USE_TO_TRADE_GREEN_STARRY_EQUIPMENT = 177, -- Use to trade GREEN starry equipment
    PARAGON_POINT = 178, -- Paragon point
    PARAGON_LEVEL = 179, -- Paragon level
    DIZZY = 180, -- Dizzy
    TOP_UP_POINT = 181, -- Top up point
    GEMS_POINT = 182, -- GEMS point
    VICTORY_POINT = 183, -- Victory point
    CALL_LIGHTNING = 184, -- Call lightning
    OVERWHELM = 185, -- Overwhelm
    BONE_ARMOR = 186, -- Bone armor
    NOEL_GIFT_APPEAR = 187, -- Noel gift appear
    NOEL_GIFT = 188, -- -Noel gift
    FIRE_ARMOR = 189, -- Fire Armor
    ANCIENT_ICE = 190, -- Ancient Ice
    PHYSICAL_ANCIENT_ICE = 191, -- Physical Ancient Ice
    SOLAR_FLARE = 192, -- Solar Flare
    PHYSICAL_SOLAR_FLARE = 193, -- Physical Solar Flare
    MAGNETIC_STORM = 194, -- Magnetic Storm
    PHYSICAL_MAGNETIC_STORM = 195, -- Physical Magnetic Storm
    POISON = 196, -- Poison
    PHYSICAL_POISON = 197, -- Physical Poison
    PHYSICAL_POISON_APPEAR = 198, -- Physical Poison appear
    POISON_APPEAR = 199, -- Poison appear
    PHYSICAL_MAGNETIC_STORM_APPEAR = 200, -- Physical Magnetic Storm appear
    MAGNETIC_STORM_APPEAR = 201, -- Magnetic Storm appear
    PHYSICAL_SOLAR_FLARE_APPEAR = 202, -- Physical Solar Flare appear
    SOLAR_FLARE_APPEAR = 203, -- Solar Flare appear
    PHYSICAL_ANCIENT_ICE_APPEAR = 204, -- Physical Ancient Ice appear
    ANCIENT_ICE_APPEAR = 205, -- Ancient Ice appear
    BOOK_USE_TO_UPGRADE_SKILL = 206, -- - Book use to upgrade skill
    INCREASE_PERCENTAGE_DAMAGE_FOR_A_SHORT_DURATION = 207, -- Increase percentage damage for a short duration
    SNOW_BLINDNESS = 208, -- Snow Blindness
    VENOM = 209, -- Venom
    SNOW_BURN_APPEAR = 210, -- Snow burn appear
    SNOW_BURN = 211, -- Snow burn
    RENOVATION = 212, -- Renovation
    PERMANENT_RENOVATION = 213, -- Permanent renovation
    RENOVATION_EXPIRY = 214, -- Renovation expiry
    IMMUNE_WEAK_PET = 215, -- Immune weak Pet
    HP_MP_REGEN_BOOST_30PCT = 216, -- HP/MP regen boost <30%
    INCREASE_OWNER_DAMAGE = 217, -- Increase owner damage
    ARMOR_PENETRATION_RESISTANCE = 218, -- Armor penetration resistance
    ACTIVATE_100PCT_DAMAGE_IMMUNITY_FOR_5S_CD_50S = 219, -- Activate 100% damage immunity for 5s (CD 50s).
    CURSE_OF_VENOM_WHEN_DEALING_50K_DAMAGE_8PCT_CHAN = 220, -- Curse of Venom: when dealing >50k damage, 8% chance to drain 10% enemy HP over 5s (CD 40s).
    CURSE_OF_EXHAUSTION_5PCT_PROC_REDUCES_ENEMY_SKIL = 221, -- Curse of Exhaustion: 5% proc, reduces enemy skill damage by 20-30% for 10s (CD 40s).
    REDUCE_PHYSICAL_RESIST = 222, -- Reduce Physical Resist
    REDUCE_FIRE_RESIST = 223, -- Reduce Fire Resist
    REDUCE_ICE_RESIST = 224, -- Reduce Ice Resist
    REDUCE_LIGHTNING_RESIST = 225, -- Reduce Lightning Resist
    REDUCE_POISON_RESIST = 226, -- Reduce Poison Resist
    IGNORE_RESIST = 227, -- Ignore Resist
    HATCHING_TIME = 228, -- Hatching Time
    HEALTH = 229, -- Health
    PUT_EGGS_IN_THE_STABLE_TO_HATCH_2 = 230, -- Put eggs in the stable to hatch
    HP = 231, -- HP
    MP = 232, -- MP
}
